# Location where configuration files will be stored.
config_dir: '~'

# Domain names configuration (related services need to be enabled).
domain_name_enable: false
domain_name: 'local'
domain_pihole: 'pihole1'          # to access pihole via: http://pihole.home.local
domain_grafana: 'grafana'        # to access grafana via: http://grafana.home.local
domain_prometheus: 'prometheus'  # to access prometheus via: http://prometheus.home.local

# Pi-hole configuration.
pihole_enable: false
pihole_hostname: pihole1
pihole_timezone: America/Denver
pihole_password: "someexamplepassword"

# Internet monitoring configuration.
monitoring_enable: true
monitoring_grafana_admin_password: "shepherd-placid4LULU"
monitoring_speedtest_interval: 60m
monitoring_ping_interval: 5s
monitoring_ping_hosts:  # [URL];[HUMAN_READABLE_NAME]
  - http://www.google.com/;google.com
  - https://github.com/;github.com
  - https://www.apple.com/;www.apple.com
  - https://www.amazon.com/;www.amazon.com
  - https://mail.proton.me/;mail.proton.me
  - https://ha.mikedembek.com/;ha.mikedembek.com

# Prometheus configuration.
prometheus_monitor_prometheus: false
prometheus_node_exporter_targets:
  - 'nodeexp:9100'
prometheus_extra_scrape_configs: ''
prometheus_tsdb_retention_time: 90d

# Shelly Plug configuration. (Also requires `monitoring_enable`)
shelly_plug_enable: false
shelly_plug_hostname: my-shelly-plug-host-or-ip
shelly_plug_http_username: username
shelly_plug_http_password: "password"

# AirGradient configuration. (Also requires `monitoring_enable`)
airgradient_enable: false
airgradient_sensors:
  # ID Should be limited to no more than 38 characters, in the set a-z.
  - id: livingroom
    ip: "192.168.0.123"
    port: 9925

# Starlink configuration. (Also requires `monitoring_enable`)
starlink_enable: false

# DNS monitoring configuration
dns_monitoring_enable: true
dns_monitoring_servers:
  - 172.17.244.10
  - 172.17.244.20
dns_monitoring_test_domains:
  - google.com
  - cloudflare.com
  - ha.mikedembek.com